baseURL = "https://sx.ix5.org/info/"
languageCode = "en-us"
title = "Open Devices Corner"
theme = "kube"
Paginate = 20

[permalinks]
    posts = "/post/:slug/"
    docs = "/:slug/"

[params]
    issoURL = "https://comments.ix5.org"
    author = "Felix"
    description = "Guides and Resources for Sony Xperia™ & AOSP"
    subdescription = "Not in any way affiliated with Sony"

[menu]
  [[menu.main]]
    name = "Docs"
    weight = 1
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "About"
    weight = 10
    url = "/about/"
  [[menu.extra]]
    name = "Community Page"
    url = "https://opendevices.ix5.org"

# Needed sice 0.60.0 or so
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      codeFences = true
      guessSyntax = false
      lineNos = false
      noClasses = true
      # See https://xyproto.github.io/splash/docs/all.html
      # and https://github.com/alecthomas/chroma
      style = "pygments"
      tabWidth = 4
